/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Sample { 
    id: number | null;
    fieldText: string | null;
    fieldTextarea: string | null;
    fieldNumber: number | null;
    fieldSwitch: boolean | null;
    fieldDate: Date | null;
    fieldSelect: number | null;
    fieldRadio: number | null;
}

